"use client";

import React from "react";

export interface IconProps {
  name: string;
  className?: string;
  size?: "sm" | "md" | "lg";
}

export const Icon = ({ 
  name, 
  className = "",
  size = "md" 
}: IconProps) => {
  const sizeClasses = {
    sm: "w-4 h-4",
    md: "w-6 h-6",
    lg: "w-8 h-8"
  };
  
  const icons: { [key: string]: string } = {
    ai: "🤖",
    analytics: "📊",
    automation: "⚡",
    design: "🎨",
    social: "📱",
    email: "📧",
    check: "✓",
    close: "×",
    arrow: "→",
    star: "★",
    heart: "♥",
    search: "🔍",
    menu: "☰",
    user: "👤",
    settings: "⚙️",
    home: "🏠",
    calendar: "📅",
    clock: "🕐",
    location: "📍",
    phone: "📞",
    mail: "📧",
    globe: "🌐",
    lock: "🔒",
    unlock: "🔓",
    eye: "👁️",
    eyeOff: "🙈",
    download: "⬇️",
    upload: "⬆️",
    share: "📤",
    like: "👍",
    dislike: "👎",
    comment: "💬",
    bookmark: "🔖",
    edit: "✏️",
    delete: "🗑️",
    plus: "+",
    minus: "-",
    play: "▶️",
    pause: "⏸️",
    stop: "⏹️",
    next: "⏭️",
    prev: "⏮️",
    volume: "🔊",
    mute: "🔇",
    fullscreen: "⛶",
    minimize: "🗗",
    maximize: "🗖",
    refresh: "🔄",
    sync: "🔄",
    wifi: "📶",
    battery: "🔋",
    signal: "📡",
    notification: "🔔",
    warning: "⚠️",
    error: "❌",
    info: "ℹ️",
    question: "❓",
    exclamation: "❗",
    success: "✅",
    rocket: "🚀",
    sparkles: "✨",
    fire: "🔥",
    lightning: "⚡",
    diamond: "💎",
    crown: "👑",
    trophy: "🏆",
    medal: "🏅",
    ribbon: "🎗️",
    gift: "🎁",
    party: "🎉",
    confetti: "🎊",
    balloon: "🎈",
    cake: "🎂",
    present: "🎁",
    tree: "🎄",
    snowflake: "❄️",
    sun: "☀️",
    moon: "🌙",
    cloud: "☁️",
    rain: "🌧️",
    thunder: "⛈️",
    rainbow: "🌈",
    flower: "🌸",
    leaf: "🍃",
    mountain: "⛰️",
    ocean: "🌊",
    beach: "🏖️",
    island: "🏝️",
    volcano: "🌋",
    desert: "🏜️",
    forest: "🌲",
    jungle: "🌴",
    savanna: "🦁",
    tundra: "🐻",
    arctic: "🐧",
    antarctic: "🐋",
    tropical: "🦜",
    temperate: "🦊",
    mediterranean: "🦅",
    alpine: "🐐",
    coastal: "🐚",
    marine: "🐠",
    freshwater: "🐟",
    terrestrial: "🦔",
    aerial: "🦅",
    aquatic: "🐋",
    arboreal: "🐒",
    fossorial: "🦡",
    nocturnal: "🦉",
    diurnal: "🦅",
    crepuscular: "🦊",
    migratory: "🦆",
    sedentary: "🐌",
    nomadic: "🐪",
    territorial: "🦁",
    solitary: "🐯",
    gregarious: "🐦",
    colonial: "🐝",
    cooperative: "🐜",
    competitive: "🦁",
    symbiotic: "🐟",
    parasitic: "🦗",
    commensal: "🦐",
    mutualistic: "🐝",
    predatory: "🦁",
    prey: "🐰",
    scavenger: "🦅",
    herbivore: "🦒",
    carnivore: "🦁",
    omnivore: "🐻",
    insectivore: "🦎",
    piscivore: "🐧",
    nectarivore: "🦋",
    frugivore: "🦜",
    granivore: "🐦",
    folivore: "🦒",
    fungivore: "🦗",
    detritivore: "🦗",
    filter: "🐋",
    browser: "🦒",
    grazer: "🦓"
  };
  
  return (
    <span className={`${sizeClasses[size]} ${className}`}>
      {icons[name] || "✨"}
    </span>
  );
}; 